### ISSUE TITLE
[FEAT] Les requêtes PUT (et DELETE ?) ne devraient pas contenir d'id d'utilisateur.

### ISSUE THREAD

**Issue by danglotb** [Bootcamp2020/skillful_network#100]
Par exemple on a :
```java
@PutMapping(value = "/usersModifPassword/{id}")
	public ResponseEntity<User> updateUserPassword(@PathVariable(value = "id") long id,
			@Valid @RequestBody UserPwdUpdateForm userModifPwd) {
...
}
```
Un utilisateur malicieux peut forger une requête et modifier le mot de passe d'un autre utilisateur.

On utilisera alors l'Annotation suivante pour récupérer l'utilisateur qui a initié la requête :
```java
@AuthenticationPrincipal User user
```

Qui sera à insérer dans les paramètres de de la méthode qui gère la requête. Par example :
```java
@PutMapping(value = "/usersModifPassword")
public ResponseEntity<User> updateUserPassword(@AuthenticationPrincipal User user,
	@Valid @RequestBody UserPwdUpdateForm userModifPwd) {
...
}
```

**Comment by DamienMonchaty** [comment]
Mise en place en cours.

Demande une optimisation du code (UserPrinciple -> User)

Exemple : 


        @PutMapping("/user")
	public ResponseEntity<User> updateUsernameCurrentUser (@AuthenticationPrincipal @Valid 
        @RequestBody User user) {

		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		User userUpdated = (User) authentication.getPrincipal();

		userUpdated.setUsername(user.getUsername());
		userRepository.save(userUpdated);
		
		return new ResponseEntity<User>(userUpdated, HttpStatus.OK);

	}

**Comment by DamienMonchaty** [comment]
Nous avons des modifications a faire comme supprimer le UserPrinciple et passer directement par le bean User.
La solution est prete cote Back, tte modif a deja ete faite par Valérie.
Nous "pusherons" cette tache quandd cela aura ete teste avec le Front car d autres changements sont necessaires : 
- Mise en place de l'appel d'API pr le Current User (/user) (Service et Home/Dashboard)
- Modification de la JwtResponse
